#!/bin/sh
#
# This script is written to help configure an axport

set -e
if [ -z "$1" ] || [ -z "$2" ]
  then echo "Usage: $0 [tty] [axport]"
  exit 1;
fi

# Init TNC (optional)
[ -z "$TNC_INIT_CMD" ] || eval "$TNC_INIT_CMD";

/usr/sbin/kissattach $1 $2 -m 256
if [ -z "$3" ] then
  exit 0; #user does not require an ip, exit
fi

/sbin/ip addr add $3 dev ax0 #should find a way to have interface name more dynamic

